export interface Quote {
  text: string
  author: string
  country: "china" | "foreign"
}

export const quotes: Quote[] = [
  // 中国名人 (50条)
  { text: "学而不思则罔，思而不学则殆", author: "孔子", country: "china" },
  { text: "千里之行，始于足下", author: "老子", country: "china" },
  { text: "天将降大任于斯人也", author: "孟子", country: "china" },
  { text: "井蛙不可语海", author: "庄子", country: "china" },
  { text: "不积跬步，无以至千里", author: "荀子", country: "china" },
  { text: "志不强者智不达", author: "墨子", country: "china" },
  { text: "千丈之堤，以蝼蚁之穴溃", author: "韩非子", country: "china" },
  { text: "人固有一死，或重于泰山", author: "司马迁", country: "china" },
  { text: "非淡泊无以明志", author: "诸葛亮", country: "china" },
  { text: "老骥伏枥，志在千里", author: "曹操", country: "china" },
  { text: "盛年不重来，一日难再晨", author: "陶渊明", country: "china" },
  { text: "天生我材必有用", author: "李白", country: "china" },
  { text: "会当凌绝顶，一览众山小", author: "杜甫", country: "china" },
  { text: "试玉要烧三日满", author: "白居易", country: "china" },
  { text: "沉舟侧畔千帆过", author: "刘禹锡", country: "china" },
  { text: "业精于勤，荒于嬉", author: "韩愈", country: "china" },
  { text: "千山鸟飞绝，万径人踪灭", author: "柳宗元", country: "china" },
  { text: "古之立大事者，不惟有超世之才", author: "苏轼", country: "china" },
  { text: "不畏浮云遮望眼", author: "王安石", country: "china" },
  { text: "忧劳可以兴国", author: "欧阳修", country: "china" },
  { text: "莫等闲，白了少年头", author: "岳飞", country: "china" },
  { text: "人生自古谁无死", author: "文天祥", country: "china" },
  { text: "知行合一", author: "王阳明", country: "china" },
  { text: "天下兴亡，匹夫有责", author: "顾炎武", country: "china" },
  { text: "天下古今之庸人，皆以一惰字致败", author: "曾国藩", country: "china" },
  { text: "发上等愿，结中等缘", author: "左宗棠", country: "china" },
  { text: "海纳百川，有容乃大", author: "林则徐", country: "china" },
  { text: "少年强则国强", author: "梁启超", country: "china" },
  { text: "时间就像海绵里的水", author: "鲁迅", country: "china" },
  { text: "怕什么真理无穷", author: "胡适", country: "china" },
  { text: "教育者，养成人格之事业也", author: "蔡元培", country: "china" },
  { text: "青年如初春，如朝日", author: "陈独秀", country: "china" },
  { text: "铁肩担道义，妙手著文章", author: "李大钊", country: "china" },
  { text: "自信人生二百年", author: "毛泽东", country: "china" },
  { text: "为中华之崛起而读书", author: "周恩来", country: "china" },
  { text: "摸着石头过河", author: "邓小平", country: "china" },
  { text: "不要失去信心，只要坚持不懈", author: "钱学森", country: "china" },
  { text: "聪明在于勤奋，天才在于积累", author: "华罗庚", country: "china" },
  { text: "攀登科学高峰，就像登山运动员", author: "陈景润", country: "china" },
  { text: "知识加汗水，成功就在前方", author: "袁隆平", country: "china" },
  { text: "今天很残酷，明天更残酷", author: "马云", country: "china" },
  { text: "从绝望中寻找希望", author: "俞敏洪", country: "china" },
  { text: "勤奋是一切事业的基础", author: "李嘉诚", country: "china" },
  { text: "最大的冒险就是不冒险", author: "马化腾", country: "china" },
  { text: "站在风口上，猪都能飞", author: "雷军", country: "china" },
  { text: "要么全力以赴，要么走人", author: "董明珠", country: "china" },
  { text: "烧不死的鸟是凤凰", author: "任正非", country: "china" },
  { text: "困难无其数，从来不动摇", author: "柳传志", country: "china" },
  { text: "把每一件简单的事做好", author: "张瑞敏", country: "china" },
  { text: "登山如人生，每一步都算数", author: "王石", country: "china" },

  // 国外名人 (50条)
  { text: "认识你自己", author: "苏格拉底", country: "foreign" },
  { text: "耐心是一切聪明才智的基础", author: "柏拉图", country: "foreign" },
  { text: "人生最终价值在于觉醒", author: "亚里士多德", country: "foreign" },
  { text: "我来了，我看见，我征服", author: "凯撒", country: "foreign" },
  { text: "生存还是毁灭", author: "莎士比亚", country: "foreign" },
  { text: "知识就是力量", author: "培根", country: "foreign" },
  { text: "我思故我在", author: "笛卡尔", country: "foreign" },
  { text: "如果我看得更远", author: "牛顿", country: "foreign" },
  { text: "生命在于运动", author: "伏尔泰", country: "foreign" },
  { text: "人生而自由", author: "卢梭", country: "foreign" },
  { text: "有两样东西，我越思考越惊奇", author: "康德", country: "foreign" },
  { text: "今天做不成的，明天也不会做好", author: "歌德", country: "foreign" },
  { text: "存在即合理", author: "黑格尔", country: "foreign" },
  { text: "人生就是痛苦", author: "叔本华", country: "foreign" },
  { text: "那些杀不死我的，使我更强大", author: "尼采", country: "foreign" },
  { text: "哲学家们只是解释世界", author: "马克思", country: "foreign" },
  { text: "物竞天择，适者生存", author: "达尔文", country: "foreign" },
  { text: "天才是百分之一的灵感", author: "爱迪生", country: "foreign" },
  { text: "弱者坐待时机，强者制造时机", author: "居里夫人", country: "foreign" },
  { text: "想象力比知识更重要", author: "爱因斯坦", country: "foreign" },
  { text: "世上只有一种英雄主义", author: "罗曼·罗兰", country: "foreign" },
  { text: "人可以被毁灭，但不能被打败", author: "海明威", country: "foreign" },
  { text: "永远，永远，永远不要放弃", author: "丘吉尔", country: "foreign" },
  { text: "我们唯一恐惧的就是恐惧本身", author: "罗斯福", country: "foreign" },
  { text: "欲变世界，先变自身", author: "甘地", country: "foreign" },
  { text: "我有一个梦想", author: "马丁·路德·金", country: "foreign" },
  { text: "生命中最伟大的时刻", author: "曼德拉", country: "foreign" },
  { text: "爱的反面不是恨，而是冷漠", author: "特蕾莎修女", country: "foreign" },
  { text: "行动是成功的阶梯", author: "毕加索", country: "foreign" },
  { text: "我梦想着绘画", author: "梵高", country: "foreign" },
  { text: "我要扼住命运的咽喉", author: "贝多芬", country: "foreign" },
  { text: "生活的苦难压不垮我", author: "莫扎特", country: "foreign" },
  { text: "音乐是上帝的礼物", author: "巴赫", country: "foreign" },
  { text: "简洁是最高的艺术", author: "肖邦", country: "foreign" },
  { text: "如果你能梦想，你就能实现", author: "迪士尼", country: "foreign" },
  { text: "活着就是为了改变世界", author: "乔布斯", country: "foreign" },
  { text: "生活不公平，你要去适应它", author: "比尔·盖茨", country: "foreign" },
  { text: "当某事足够重要时", author: "马斯克", country: "foreign" },
  { text: "别人贪婪时我恐惧", author: "巴菲特", country: "foreign" },
  { text: "最大的风险是不冒风险", author: "扎克伯格", country: "foreign" },
  { text: "善良比聪明更难", author: "贝佐斯", country: "foreign" },
  { text: "你见过凌晨四点的洛杉矶吗", author: "科比", country: "foreign" },
  { text: "我可以接受失败", author: "乔丹", country: "foreign" },
  { text: "不做下一个谁，做第一个自己", author: "詹姆斯", country: "foreign" },
  { text: "天赋决定上限，努力决定下限", author: "费德勒", country: "foreign" },
  { text: "我不是天生强大，我只是天生要强", author: "梅西", country: "foreign" },
  { text: "你的爱让我变得更强大", author: "C罗", country: "foreign" },
  { text: "每个人都有计划", author: "泰森", country: "foreign" },
  { text: "不可能这个词，只在愚人字典里", author: "阿里", country: "foreign" },
  { text: "活着就有希望", author: "霍金", country: "foreign" },
]

export const chinaQuotes = quotes.filter((q) => q.country === "china")
export const foreignQuotes = quotes.filter((q) => q.country === "foreign")
